### ISSUE TITLE
脚本部分

### ISSUE THREAD

**Issue by wen-fei** [wen-fei/choice#4]
网盘链接不稳定，需要的加qq

**Comment by yifanzheng** [comment]
QQ是多少啊？

**Comment by wen-fei** [comment]
近期要准备春招，这个项目我好好整理一下，再统一发出来

**Comment by yifanzheng** [comment]
好的，谢谢你啦！

________________________________
发件人: TengYun <notifications@github.com>
发送时间: Wednesday, December 19, 2018 8:59:47 PM
收件人: wen-fei/choice
抄送: Star.Y.Zheng; Comment
主题: Re: [wen-fei/choice] 脚本部分 (#4)


近期要准备春招，这个项目我好好整理一下，再统一发出来

―
